DELETE DATABASE IF EXISTS qcm_app;
CREATE DATABASE IF NOT EXISTS qcm_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE qcm_app;

CREATE TABLE IF NOT EXISTS utilisateurs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    role ENUM('user', 'admin') DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    reponse1 VARCHAR(255) NOT NULL,
    reponse2 VARCHAR(255) NOT NULL,
    reponse3 VARCHAR(255) NOT NULL,
    reponse4 VARCHAR(255) NOT NULL,
    bonne_reponse INT NOT NULL CHECK (bonne_reponse BETWEEN 1 AND 4),
    categorie VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS tentatives (
    id INT AUTO_INCREMENT PRIMARY KEY,
    utilisateur_id INT NOT NULL,
    score FLOAT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reponses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tentative_id INT NOT NULL,
    question_id INT NOT NULL,
    reponse_utilisateur INT NOT NULL,
    correcte BOOLEAN NOT NULL,
    FOREIGN KEY (tentative_id) REFERENCES tentatives(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

INSERT INTO utilisateurs (nom, prenom, email, mot_de_passe, role)
VALUES ('Admin', 'Super', 'admin@qcm.local', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin');

INSERT INTO questions (question, reponse1, reponse2, reponse3, reponse4, bonne_reponse, categorie)
VALUES 
('Que signifie PHP ?', 'Personal Home Page', 'PHP: Hypertext Preprocessor', 'Private Hosting Platform', 'Programmer HTML Pages', 2, 'Programmation Web'),
('Quel attribut HTML est utilisé pour définir un style en ligne ?', 'class', 'styles', 'font', 'style', 4, 'HTML/CSS'),
('Quelle fonction PHP est utilisée pour vérifier si une variable est définie et non nulle ?', 'isset()', 'empty()', 'is_null()', 'defined()', 1, 'PHP'),
('Que signifie l''acronyme CSS ?', 'Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style Sheets', 'Colorful Style Sheets', 2, 'HTML/CSS'),
('Quel est le rôle principal de JavaScript dans une page web ?', 'Stocker les données côté serveur', 'Mettre en forme le texte', 'Rendre la page interactive', 'Gérer la base de données', 3, 'JavaScript'),
('Comment déclare-t-on une variable en PHP ?', 'var nom = "Valeur";', '$nom = "Valeur";', 'let nom = "Valeur";', 'variable nom = "Valeur";', 2, 'PHP'),
('En SQL, quelle instruction permet d''extraire des données d''une base ?', 'EXTRACT', 'GET', 'PULL', 'SELECT', 4, 'Base de données'),
('Quel port réseau est utilisé par défaut pour le protocole HTTP ?', '21', '443', '80', '8080', 3, 'Réseau'),
('Quelle balise HTML est utilisée pour inclure un fichier JavaScript externe ?', '<javascript>', '<script>', '<js>', '<link>', 2, 'HTML/CSS'),
('Dans l''architecture MVC, que signifie la lettre "M" ?', 'Module', 'Macro', 'Modèle', 'Main', 3, 'Architecture Web');
('Quel langage est principalement utilisé pour structurer le contenu d''une page web ?', 'CSS', 'HTML', 'JavaScript', 'SQL', 2, 'HTML/CSS'),
('Quelle propriété CSS permet de changer la couleur du texte ?', 'background-color', 'font-size', 'color', 'text-style', 3, 'HTML/CSS'),
('Quelle méthode HTTP est généralement utilisée pour envoyer des données d''un formulaire ?', 'GET', 'POST', 'DELETE', 'HEAD', 2, 'Web'),
('En PHP, quel symbole est utilisé devant le nom d''une variable ?', '#', '@', '$', '&', 3, 'PHP'),
('Quelle fonction PHP permet d''afficher du texte à l''écran ?', 'printText()', 'echo', 'display()', 'show()', 2, 'PHP'),
('Quelle instruction SQL permet d''ajouter des données dans une table ?', 'ADD', 'INSERT INTO', 'CREATE', 'UPDATE', 2, 'Base de données'),
('Quelle clause SQL est utilisée pour filtrer les résultats ?', 'ORDER BY', 'GROUP BY', 'WHERE', 'LIMIT', 3, 'Base de données'),
('Quelle commande SQL permet de modifier des données existantes ?', 'CHANGE', 'MODIFY', 'UPDATE', 'ALTER', 3, 'Base de données'),
('Quel type de clé permet d''identifier de manière unique une ligne dans une table ?', 'Clé étrangère', 'Clé primaire', 'Clé secondaire', 'Clé publique', 2, 'Base de données'),
('Quelle instruction SQL permet de supprimer une table ?', 'DELETE TABLE', 'REMOVE TABLE', 'DROP TABLE', 'CLEAR TABLE', 3, 'Base de données'),
('Quelle balise HTML permet de créer un lien hypertexte ?', '<a>', '<link>', '<href>', '<url>', 1, 'HTML/CSS'),
('Quelle balise HTML permet d''insérer une image ?', '<picture>', '<image>', '<img>', '<src>', 3, 'HTML/CSS'),
('Quelle propriété CSS permet de modifier la taille du texte ?', 'text-size', 'font-size', 'size', 'font-style', 2, 'HTML/CSS'),
('Quelle propriété CSS permet de centrer le texte ?', 'align', 'text-align', 'center-text', 'justify-content', 2, 'HTML/CSS'),
('Quelle valeur CSS rend un élément invisible sans supprimer son espace ?', 'display: none;', 'visibility: hidden;', 'opacity: 100;', 'hidden: true;', 2, 'HTML/CSS'),
('En JavaScript, quelle fonction permet d''afficher un message dans la console ?', 'print()', 'echo()', 'console.log()', 'message()', 3, 'JavaScript'),
('Quel mot-clé JavaScript permet de déclarer une variable modifiable ?', 'const', 'let', 'static', 'define', 2, 'JavaScript'),
('Quel opérateur JavaScript permet de comparer la valeur et le type ?', '==', '=', '===', '!=', 3, 'JavaScript'),
('Quel événement JavaScript se déclenche lorsqu''un utilisateur clique sur un élément ?', 'onhover', 'onchange', 'onclick', 'onload', 3, 'JavaScript'),
('Quel format est souvent utilisé pour échanger des données entre un serveur et un client web ?', 'HTML', 'JSON', 'CSS', 'PNG', 2, 'Web');
('Quelle balise HTML définit le titre principal d''une page ?', '<title>', '<h1>', '<head>', '<header>', 2, 'HTML/CSS'),
('Quelle balise HTML contient les métadonnées d''une page ?', '<body>', '<main>', '<head>', '<footer>', 3, 'HTML/CSS'),
('Quelle balise HTML contient le contenu visible d''une page ?', '<head>', '<body>', '<meta>', '<style>', 2, 'HTML/CSS'),
('Quelle balise HTML permet de créer une liste ordonnée ?', '<ul>', '<ol>', '<li>', '<list>', 2, 'HTML/CSS'),
('Quelle balise HTML permet de créer une liste non ordonnée ?', '<ol>', '<ul>', '<li>', '<list>', 2, 'HTML/CSS'),
('Quelle balise HTML représente un élément de liste ?', '<item>', '<li>', '<ul>', '<ol>', 2, 'HTML/CSS'),
('Quel attribut HTML est utilisé pour indiquer l''URL d''un lien ?', 'src', 'href', 'alt', 'link', 2, 'HTML/CSS'),
('Quel attribut HTML est utilisé pour indiquer la source d''une image ?', 'href', 'alt', 'src', 'source', 3, 'HTML/CSS'),
('Quel attribut HTML fournit un texte alternatif pour une image ?', 'title', 'alt', 'placeholder', 'name', 2, 'HTML/CSS'),
('Quelle balise HTML permet de créer un formulaire ?', '<input>', '<form>', '<button>', '<fieldset>', 2, 'HTML/CSS'),
('Quelle balise HTML permet de créer un champ de saisie ?', '<input>', '<textarea>', '<select>', '<label>', 1, 'HTML/CSS'),
('Quelle balise HTML permet de créer une zone de texte multiligne ?', '<input>', '<textarea>', '<select>', '<option>', 2, 'HTML/CSS'),
('Quelle balise HTML permet de créer une liste déroulante ?', '<dropdown>', '<select>', '<option>', '<list>', 2, 'HTML/CSS'),
('Quelle balise HTML définit une option dans une liste déroulante ?', '<select>', '<input>', '<option>', '<choice>', 3, 'HTML/CSS'),
('Quel attribut HTML permet d''afficher un texte indicatif dans un champ ?', 'value', 'placeholder', 'label', 'title', 2, 'HTML/CSS'),
('Quelle balise HTML est utilisée pour créer un bouton ?', '<button>', '<input>', '<click>', '<submit>', 1, 'HTML/CSS'),
('Quelle balise HTML permet d''insérer une ligne horizontale ?', '<br>', '<hr>', '<line>', '<border>', 2, 'HTML/CSS'),
('Quelle balise HTML permet d''effectuer un retour à la ligne ?', '<br>', '<hr>', '<p>', '<newline>', 1, 'HTML/CSS'),
('Quelle balise HTML définit un paragraphe ?', '<p>', '<paragraph>', '<text>', '<span>', 1, 'HTML/CSS'),
('Quelle balise HTML est généralement utilisée pour un conteneur générique en bloc ?', '<span>', '<div>', '<section>', '<article>', 2, 'HTML/CSS'),
('Quelle balise HTML est généralement utilisée pour un conteneur générique en ligne ?', '<div>', '<span>', '<main>', '<aside>', 2, 'HTML/CSS'),
('Quelle propriété CSS change la couleur d''arrière-plan ?', 'color', 'background-color', 'font-color', 'bg', 2, 'HTML/CSS'),
('Quelle propriété CSS change la police d''écriture ?', 'font-family', 'font-size', 'text-font', 'family', 1, 'HTML/CSS'),
('Quelle propriété CSS met le texte en gras ?', 'font-style', 'font-weight', 'text-decoration', 'bold', 2, 'HTML/CSS'),
('Quelle propriété CSS souligne le texte ?', 'font-weight', 'text-align', 'text-decoration', 'line-height', 3, 'HTML/CSS'),
('Quelle propriété CSS contrôle les marges extérieures ?', 'padding', 'margin', 'border', 'spacing', 2, 'HTML/CSS'),
('Quelle propriété CSS contrôle les marges intérieures ?', 'margin', 'padding', 'border', 'outline', 2, 'HTML/CSS'),
('Quelle propriété CSS définit la bordure d''un élément ?', 'outline', 'border', 'margin', 'padding', 2, 'HTML/CSS'),
('Quelle propriété CSS arrondit les coins d''un élément ?', 'border-round', 'corner-radius', 'border-radius', 'radius', 3, 'HTML/CSS'),
('Quelle propriété CSS contrôle la largeur d''un élément ?', 'height', 'width', 'size', 'length', 2, 'HTML/CSS'),
('Quelle propriété CSS contrôle la hauteur d''un élément ?', 'width', 'height', 'size', 'top', 2, 'HTML/CSS'),
('Quelle valeur CSS permet de masquer complètement un élément sans garder son espace ?', 'display: none;', 'visibility: hidden;', 'opacity: 0;', 'hidden: false;', 1, 'HTML/CSS'),
('Quelle propriété CSS permet de créer une mise en page flexible ?', 'grid', 'float', 'flex', 'position', 3, 'HTML/CSS'),
('Quelle valeur de display active Flexbox ?', 'display: block;', 'display: inline;', 'display: flex;', 'display: grid;', 3, 'HTML/CSS'),
('Quelle propriété Flexbox aligne les éléments sur l''axe principal ?', 'align-items', 'justify-content', 'flex-direction', 'gap', 2, 'HTML/CSS'),
('Quelle propriété Flexbox aligne les éléments sur l''axe secondaire ?', 'justify-content', 'align-items', 'flex-wrap', 'order', 2, 'HTML/CSS'),
('Quelle valeur de position place un élément par rapport à son parent positionné ?', 'static', 'relative', 'absolute', 'fixed', 3, 'HTML/CSS'),
('Quelle valeur de position fixe un élément par rapport à la fenêtre ?', 'relative', 'absolute', 'fixed', 'sticky', 3, 'HTML/CSS'),
('Quelle propriété CSS contrôle l''ordre de superposition ?', 'index', 'z-index', 'layer', 'position-index', 2, 'HTML/CSS'),
('Quelle propriété CSS permet d''ajouter une ombre au texte ?', 'box-shadow', 'text-shadow', 'shadow-text', 'font-shadow', 2, 'HTML/CSS'),
('Quelle propriété CSS permet d''ajouter une ombre à une boîte ?', 'text-shadow', 'box-shadow', 'border-shadow', 'element-shadow', 2, 'HTML/CSS'),
('En PHP, quelle balise ouvre généralement un bloc de code PHP ?', '<?php', '<php>', '<?', '<script php>', 1, 'PHP'),
('Quelle fonction PHP permet de connaître la longueur d''une chaîne ?', 'count()', 'strlen()', 'length()', 'size()', 2, 'PHP'),
('Quelle fonction PHP permet de compter les éléments d''un tableau ?', 'strlen()', 'count()', 'array_length()', 'sizeof_string()', 2, 'PHP'),
('Quelle superglobale PHP contient les données envoyées par la méthode POST ?', '$_GET', '$_POST', '$_SESSION', '$_SERVER', 2, 'PHP'),
('Quelle superglobale PHP contient les données envoyées dans l''URL ?', '$_POST', '$_GET', '$_FILES', '$_COOKIE', 2, 'PHP'),
('Quelle superglobale PHP permet de gérer les sessions ?', '$_SESSION', '$_SERVER', '$_ENV', '$_REQUEST', 1, 'PHP'),
('Quelle fonction PHP démarre une session ?', 'start_session()', 'session_start()', 'begin_session()', 'open_session()', 2, 'PHP'),
('Quelle fonction PHP permet de rediriger vers une autre page via un en-tête HTTP ?', 'redirect()', 'header()', 'location()', 'go()', 2, 'PHP'),
('Quelle fonction PHP permet de hacher un mot de passe ?', 'password_hash()', 'hash_password()', 'md5_password()', 'crypt_password()', 1, 'PHP'),
('Quelle fonction PHP permet de vérifier un mot de passe haché ?', 'password_check()', 'password_verify()', 'verify_hash()', 'check_password()', 2, 'PHP'),
('Quel opérateur PHP permet de concaténer des chaînes ?', '+', '.', '&', '||', 2, 'PHP'),
('Quelle structure PHP permet de répéter un bloc tant qu''une condition est vraie ?', 'if', 'while', 'switch', 'foreach', 2, 'PHP'),
('Quelle boucle PHP est particulièrement utilisée pour parcourir un tableau ?', 'for', 'while', 'foreach', 'switch', 3, 'PHP'),
('Quelle instruction PHP permet d''inclure un fichier et provoque une erreur fatale si le fichier est absent ?', 'include', 'require', 'import', 'load', 2, 'PHP'),
('Quelle extension PHP est souvent utilisée pour se connecter à MySQL avec des requêtes préparées ?', 'PDO', 'FTP', 'GD', 'XML', 1, 'PHP'),
('En SQL, quelle clause permet de trier les résultats ?', 'WHERE', 'ORDER BY', 'GROUP BY', 'HAVING', 2, 'Base de données'),
('En SQL, quelle clause permet de regrouper des lignes ?', 'ORDER BY', 'GROUP BY', 'WHERE', 'LIMIT', 2, 'Base de données'),
('En SQL, quelle fonction calcule le nombre de lignes ?', 'SUM()', 'COUNT()', 'AVG()', 'MAX()', 2, 'Base de données'),
('En SQL, quelle fonction calcule une moyenne ?', 'COUNT()', 'SUM()', 'AVG()', 'MIN()', 3, 'Base de données'),
('En SQL, quelle instruction permet de créer une table ?', 'MAKE TABLE', 'CREATE TABLE', 'NEW TABLE', 'ADD TABLE', 2, 'Base de données'),
('En SQL, quelle instruction permet de supprimer des lignes d''une table ?', 'DROP', 'DELETE', 'REMOVE DATABASE', 'CLEAR COLUMN', 2, 'Base de données'),
('En SQL, quelle clause limite le nombre de résultats retournés ?', 'LIMIT', 'SHORT', 'TOP', 'MAXROWS', 1, 'Base de données'),
('Quelle contrainte SQL empêche les valeurs dupliquées dans une colonne ?', 'NOT NULL', 'UNIQUE', 'DEFAULT', 'CHECK', 2, 'Base de données'),
('Quelle contrainte SQL oblige une colonne à avoir une valeur ?', 'UNIQUE', 'DEFAULT', 'NOT NULL', 'AUTO_INCREMENT', 3, 'Base de données'),
('Quelle clé SQL sert à relier une table à une autre ?', 'Clé primaire', 'Clé étrangère', 'Clé unique', 'Clé locale', 2, 'Base de données'),
('Quel type SQL est souvent utilisé pour stocker du texte long ?', 'INT', 'VARCHAR', 'TEXT', 'BOOLEAN', 3, 'Base de données'),
('Quel type SQL est souvent utilisé pour stocker une date et une heure ?', 'DATEONLY', 'DATETIME', 'TIMEINT', 'VARCHAR', 2, 'Base de données'),
('Quel mot-clé SQL est utilisé pour éviter les doublons dans les résultats ?', 'UNIQUE', 'DISTINCT', 'DIFFERENT', 'ONLY', 2, 'Base de données'),
('Quelle jointure SQL retourne uniquement les lignes correspondantes dans les deux tables ?', 'LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN', 3, 'Base de données');